LABEL_MAPPING = {
    'strike_and_dip': ['strike_dip_bedding_pt',
                       'strikedip_pt',
                       'strike_dip',
                       'inclined_bedding_pt',
                       'incl_or_imp_bedding_p',
                       'AZ_HouseRock_MF2364_bedding_pt',
                       'implied_bedding_pt',
                       'AZ_PeachSprings_bedding_pt',
                       'bedding_top_known_pt',
                       'bedding_inclined_pt',
                       'AK_Ikpikpuk_inclined_pt',
                       'AK_Valdez_Inclined_pt',
                       'inclbed_pt',
                       'AZ_Cane_basemap_inclined_pt.tif',
                       'Inclined_bedding_-_S_pt',
                       'bedding_inclined_pt',
                       'strike_dip_beds_pt',
                       'CA_InyoMtns_bedding_pt',],

    'horizontal_bedding': ['horiz_bedding_pt',
                           'horizontal_pt',
                           'bedding_horizontal_pt',
                           'AK_Ikpikpuk_horizontal_pt.tif',
                           'AK_PointLay_Horizontal_pt',
                           'AR_Buffalo_west_horizbed_pt',
                           'horzbed_pt',
                           'horizbed_pt',
                           'horiz_bedding_pt',
                           'Horizontal_bedding_pt',
                           'horizon_bedding_pt',
                          ],
    # 'approximate_bedding': ['bedding_approx_pt',  ],
    # 'estimated_bedding': ['AK_Ikpikpuk_estimated_pt.tif', ],
    'overturned_bedding': ['overturned_bedding_pt',
                           'overturned_pt',
                           'bedding_overturned_pt',
                           'overturn_bedding_pt',
                           'Overturned_bedding_-_pt',],
    'vertical_bedding': ['vertical_bedding_pt',
                         'vertical_pt',
                         'vertical_top_pt',
                         'bedding_vertical_pt',
                         'Vertical_bedding_-_S_p' ,
                         ],
#    'mine_shaft': ['geo_mosaic_2_pt', ],
#    'prospect_pit': ['geo_mosaic_3_pt', ],
}
