# Dockerfile for geo referencing on TASKS

# NOTE: must be run with build context ../../tasks/geo_referencing

FROM  docker-hub.uncharted.software/python:3.9-slim 

RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ python3-dev git ffmpeg libsm6 libxext6 

# Create needed directories for geo referencing task(s)
ARG TASKS_DIR=/app/tasks/geo_referencing/
RUN mkdir -p ${TASKS_DIR}
WORKDIR ${TASKS_DIR}

COPY requirements.txt setup.cfg pyproject.toml ./

# install requirements
RUN pip install --upgrade pip --no-cache-dir
RUN pip install --no-cache-dir -r requirements.txt

# Copy over geo referencing tasks code
COPY src/ ./src/

CMD ["bash"]

